[package]
name = "lessord"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "lessor 的服务进程：DHCP 引擎 + HTTP/WebSocket API"

[dependencies]
lessor-core.workspace = true
lessor-net.workspace = true
discovery.workspace = true
rust-embed.workspace = true
dhcproto.workspace = true
tokio.workspace = true
axum.workspace = true
socket2.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
ipnet.workspace = true
